---
slug: GoBootcamp
filename: GoBootcamp
title: Go Bootcamp
subtitle: Everything you need to know to get started with Go.
description: Companion book to the Go Bootcamp event.
author: Matt Aimonetti
copyright: 2014
uuid: da01cd68-2c21-4ca9-9552-e15dca498dce
pdf_preview_page_range: 1..4
epub_mobi_preview_chapter_range: 0..1
