---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        Optimized for Kindle and iPad
        Almost 9000 pages of content
        Includes a free copy of 1st Edition PDF
    media:
      - html
      - pdf
      - epub
      - mobi
    price: 3500

  -
    code: screencasts
    name: "HTML & Screencasts"
    description:
      |
        Full updated for the 2nd edition
        100% DRM-free digital downloads
        (QuickTime and Ogg Vorbis)
        Includes first edition screencasts
    media:
      - html
      - screencasts
    price: 12500

  -
    code: all
    name: "HTML, Ebook, and Screencasts"
    description:
      |
        Includes all 50 screencasts
        eBook formats for Kindle, Nook, and PDF
        Read online.
    media:
      - html
      - pdf
      - epub
      - mobi
      - screencasts
    price: 12500
    regular_price: 19900

authors:
  -
    name: "Matt Aimonetti"
    image: /images/matt_aimonetti_sq_2013_small.jpg
    contact_email: "mattaimonetti@gmail.com"
    bio:
      |
        Matt is [Splice](https://splice.com) cofounder.
        He's an active community member who contributed to many projects including the Go language. Matt is also a published author and who maintains his 
         [personal blog](http://matt.aimonetti.net) about tech and programming in general.

testimonials:
  -
    name: "Evan Phoenix"
    title: "Code Chef / Mad Scientist"
    image: /images/evan.jpeg
    text: "I'm sure this book is great, but I didn't read it."

marketing_content: ''

contact_email: ''
hide_custom_domain_footer: false
